### PR TITLE
V3

### PR DESCRIPTION
**Pull request by brendt**
This PR is now ready for review. I want to tag v3 soon.

- Require `php:^8.0`
- Removed all runtime type checking functionality, you should use typed properties and a static analysis tool like Psalm or PhpStan
- Removed `Spatie\DataTransferObject\DataTransferObjectCollection`
- Removed `Spatie\DataTransferObject\FlexibleDataTransferObject`, all DTOs are now considered flexible 
- Added `Spatie\DataTransferObject\Validator`
- Added `Spatie\DataTransferObject\Validation\ValidationResult`
- Added `#[DefaultCast]`
- Added `#[CastWith]`
- Added `Spatie\DataTransferObject\Caster`
- Added `#[Strict]`

Also check the README: https://github.com/spatie/data-transfer-object/tree/v3

### CODE REVIEW

**Comment by mfn** [comment]
Not everyone can jump on PHP8, i there a plan for V2? Regarding "maintenance", "bug fixes" (although it's probably low, still).

Will you keep a v2 branch around for such possible releases?

**Comment by brendt** [comment]
> Will you keep a v2 branch around for such possible releases?

I'll make a separate v2 branch that we can keep updating if necessary, only bugfixes though, I don't want to maintain new features.

**Comment by mfn** [comment]
Nice, thanks! 👍

**Comment by brendt** [comment]
I also added a `#[Strict]` attribute:

```php
class NonStrictDto extends DataTransferObject
{
    public string $name;
}

// This works
new NonStrictDto(
    name: 'name',
    unknown: 'unknown'
);
```

```php
use \Spatie\DataTransferObject\Attributes\Strict;

#[Strict]
class StrictDto extends DataTransferObject
{
    public string $name;
}

// This throws a \Spatie\DataTransferObject\Exceptions\UnknownProperties exception
new StrictDto(
    name: 'name',
    unknown: 'unknown'
);
```

**Comment by brendt** [comment]
Also one final change: added `ValidationResult::valid()` and `ValidationResult::invalid(string $message)`

**Comment by brendt** [comment]
Todo: 

- [ ] Add `toArray`

**Comment by morrislaptop** [comment]
Is there any way to get constructor argument type hints in editors?

**Comment by mugisham** [comment]
Out of curiosity, when will this be released

**Comment by brendt** [comment]
> Is there any way to get constructor argument type hints in editors?

@morrislaptop Not as far as I'm aware :( Maybe you could use promoted properties, but you'd need to manually call `parent::__construct(func_get_args())` or something alike…

**Comment by brendt** [comment]
> Out of curiosity, when will this be released

@mugisham today, probably :)

**Comment by brendt** [comment]
Merged and released: https://github.com/spatie/data-transfer-object/releases/tag/3.0.0

**Comment by mfn** [comment]
Congratulations!

Nice to see the evolution of the package, wow. Though I'm not be able to use it for a while, I'm excited looking forward to that time.

Thanks!

**Comment by mfn** [comment]
Pinging @atymic and @anteris-dev as their tools are listed in https://github.com/spatie/data-transfer-object#external-tools (from the V2 version) but they are _probably_ not compatible anymore

**Comment by atymic** [comment]
@mfn all done for v3 on the website and cli tool :)

**Pull request merged**
