### PR TITLE
feat: interpret php 7.4 types

### PR DESCRIPTION
**Pull request by skyrpex**
Closes https://github.com/spatie/data-transfer-object/issues/98

### CODE REVIEW

**Comment by skyrpex** [comment]
Didn't notice that it should conditionally support other PHP versions... working on it.

**Comment by skyrpex** [comment]
Also, need to adapt the tests...

**Comment by skyrpex** [comment]
@brendt sorry, I'm not sure how to proceed with the testing. There are some tests that expect the constructor to accept a doc comment, but in my later changes the constructor just accepts a ReflectionProperty.

Maybe I could add another static constructor (fromDocComment, which would be called from fromReflectionProperty), and also change the constructor to just accept the definition directly.

**Comment by mfn** [comment]
Doesn't this compete with https://github.com/spatie/data-transfer-object/pull/77 🤔

**Comment by brendt** [comment]
I haven't looked into this in depth. I'll try my best to tag v2 soon, but I can't make any promises on a deadline.

**Comment by brendt** [comment]
Closed in favour of https://github.com/spatie/data-transfer-object/pull/106

**Pull request closed without merging**
