### PR TITLE
Transform DTO with DataTransformer

### PR DESCRIPTION
**Pull request by coldic3**
I find it very helpful to transform the entire DTO during initialization and achieve ready to use DTO. `DataTransformer` can be used in `#[TransformWith]` attribute.

### CODE REVIEW

**Comment by brendt** [comment]
Can you give an example of what this PR does?

**Comment by brendt** [comment]
Why not add a static constructor on the DTO itself?

**Comment by coldic3** [comment]
I didn't think about it TBH. For sure it's much more simple but still see some advantages of a transformer. It's another responsibility and it's good to have it in a separate object, transformers are reusable, can transform only part of args and let mappers do the rest.

**Comment by brendt** [comment]
From my side, it's quite a lot of extra code to maintain, while I think static constructors are a perfectly fine solution. So I won't merge this in for now.

**Pull request closed without merging**
