### PR TITLE
Convert already nicely documented regex to true multi-line regex

### PR DESCRIPTION
**Pull request by mfn**
I mean, it's already there, right? :-)

### CODE REVIEW

**Comment by brendt** [comment]
See, now I'm confused: I tried exactly this, and all tests failed, which is why I moved the docs to the comments 🤔

**Comment by brendt** [comment]
Oh, is that what the `x` modifier does?

**Comment by jdreesen** [comment]
It is, see `PCRE_EXTENDED` here: https://www.php.net/manual/en/reference.pcre.pattern.modifiers.php

**Comment by brendt** [comment]
TIL! 

Thanks!

**Comment by mfn** [comment]
❤️ 

Yeah, I too use like once in 5 years or so…

**Pull request merged**
